### PR TITLE
Losslessly compress images via Picabot

### PR DESCRIPTION
**Pull request by lukateras**
Hello! It is [**Picabot**, an automatic GitHub image optimizer](https://github.com/somu/picabot).

Your repository cointains some images, and I compressed them for you.
Do not worry: the compression is lossless and uses [ImageOptim](http://imageoptim.com) toolkit.

This bot exists to make the Internet faster. There are people who've got a fast internet connection,
but there are countries where additional 50 KBs take a reasonable time to download (like additional 2-3 minutes).
Additionally, this PR is going to save some precious disk space and decrease your server load. Picabot saves
approximately 25% of space. Still, if you do not need your images optimized, feel free to close this pull request.

If I have enough money, I'll build a server which will send these precious pull requests much faster.
And if I had monthly donations, I would dedicate all my work time to open-source, so donations are very appreciated.

[Donate](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=ZXESQ83MM3H78)

Pull requests, forks and favs are welcome: https://github.com/somu/picabot

### CODE REVIEW

**Comment by A** [comment]
@somu Hi! Thank you for PR, but what wrong with the branch?

**Comment by A** [comment]
@somu 
- 1,257 additions
- 838 deletions

**Comment by lukateras** [comment]
It seems that my bot currently doesn’t play well with GitHub repos where the default branch is not `master`. My apologies. I will close this now and, if you want, process your repo one more time when the issue is fixed.

**Comment by A** [comment]
Ok, that would be great

**Comment by A** [comment]
Paypal doesn't loves us:

> The payment you initiated has been blocked because PayPal can only facilitate payments between Russian residents when they transact in Russian Ruble. Please go back to the merchant website and choose to pay in Russian Ruble, or alternatively choose another payment method.

**Comment by lukateras** [comment]
It’s a pity. Got a rouble button though:

[Донат](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=HGN4CX7EYYW7Y)

**Pull request closed without merging**
